<?php

use Illuminate\Database\Seeder;

class StoresTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $param = [
            'store_name' => 'じんた',
            'address' => '大分県大分市要町1-14',
            'link' => 'https://jinta.oita.jp',
            'tel' => '097-574-8429',
            'service' => '炭火で焼き上げえるもも焼き。とりの旨味と炭火の香りが抜群',
            'picture1' => 'https://www.oitadrip.jp/zwp/wp-content/uploads/2022/02/jinta1-1024x683.jpg',
            'picture2' => 'https://www.tts01.jp/api_img/contents/shopinfo/apo01/fc7b18064a340766ce151ef404e975e5_01_01.jpg',
            'picture3' => 'https://stat.ameba.jp/user_images/20220731/08/abcenter/23/e1/j/o0900067515153996206.jpg?caw=800',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23321',
            'longitude' => '131.60560',
            'review_count' => '12',
            'star' => '3',
            'end_time' => '0:00',
            'start_time' => '11:00'
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'おめでたい',
            'address' => '大分県大分市末広1丁目1-5末光ビル',
            'link' => 'https://omedetai.info/',
            'tel' => '080-2782-2151',
            'service' => '二代目が作る「こってり豚骨」が看板メニューです。一杯で満足できるほど濃厚な味わいはクセになること間違いなし。長時間炊き続ける濃厚豚骨、スープに絡む自家製麺、味わい深い極厚チャーシューがこだわりです。',
            'picture1' => 'https://oita-journey.com/wp-content/uploads/2022/07/4E73DC91-A885-4475-81E7-D900E48DFD9F-800x600.jpeg',
            'picture2' => 'https://trinita-kouenkai.net/wp01/wp-content/uploads/2020/11/omedetai_2.jpg',
            'picture3' => 'https://www.oitadrip.jp/zwp/wp-content/uploads/2020/11/3-3.jpg',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23420',
            'longitude' => '131.60578',
            'review_count' => '8',
            'star' => '4',
            'end_time' => '23:30',
            'start_time' => '11:00'
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'みのりみのる',
            'address' => '大分県大分市要町1-14 アミュプラザおおいた 1F',
            'link' => 'https://www.minoriminoru.jp/',
            'tel' => '097-535-8623',
            'service' => '生産者と生活者がお互いを想い食と農を通じて共感する・・・みのりみのるプロジェクトはそんな場や機会を提案します。',
            'picture1' => 'https://phrase-oita.com/wp-content/uploads/2018/12/20181212114.jpg',
            'picture2' => 'https://www.zennoh.or.jp/shop/upload_files/minoriminoru_oita_2.jpg',
            'picture3' => 'https://media-cdn.tripadvisor.com/media/photo-s/1d/95/54/8e/caption.jpg',
            'picture4' => '',
            'parking' => '有',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23382',
            'longitude' => '1313.60580',
            'review_count' => '10',
            'star' => '4',
            'end_time' => '22:00',
            'start_time' => '10:00',
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'ヒョンチャンプルコギ',
            'address' => '大分県大分市要町1-14 JR大分シティ 1F 豊後にわさきいっぷく横丁',
            'link' => 'https://y266617.gorp.jp/',
            'tel' => '0978-513-2850',
            'service' => '店内はカウンター席、テーブル席、個室と3種類のお席をご用意しております! どの席も本場韓国の屋台を彷彿とさせるハングルの看板や、電球がチャミスルの瓶で出来てたりと、非日常の空間を過ごしていただけます！',
            'picture1' => 'https://images.keizai.biz/oita_keizai/headline/1655946910_photo.jpg',
            'picture2' => 'https://www.tts01.jp/api_img/contents/shopinfo/apo01/320ffd223d8e08df177612614a5b39b8_01_01.jpg',
            'picture3' => 'https://prtimes.jp/i/55529/13/resize/d55529-13-f1947974660c870e3e2e-0.jpg',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23379',
            'longitude' => '131.60598',
            'review_count' => '13',
            'star' => '3',
            'end_time' => '20:00',
            'start_time' => '10:00',
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'ふくや',
            'address' => '大分県大分市末広町1丁目1-25',
            'link' => 'https://fukuya-ramen.com/',
            'tel' => '097-538-5165',
            'service' => '一、48時間煮込み、継ぎ足し継ぎ足し自慢のスープ。 二、低温調理したロース肉の極上チャーシュー 三、スープとの相性を抜群に活かしたここでしか味わえない自家製麺 四、メンマでなくコリコリした食感がたまらないタケノコ',
            'picture1' => 'https://phrase-oita.com/manage/wp-content/uploads/2016/05/20210402246.jpg',
            'picture2' => 'https://cospashima.com/wp-content/uploads/2020/01/suehiromachi-fukuya_09.jpg',
            'picture3' => 'https://tblg.k-img.com/restaurant/images/Rvw/90031/640x640_rect_90031639.jpg',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23469',
            'longitude' => '131.60659',
            'review_count' => '7',
            'star' => '4',
            'end_time' => '22:00',
            'start_time' => '11:00'
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'ホテルショコラ',
            'address' => '大分県大分市要町1-14 アミュプラザおおいた 1F',
            'link' => ' https://hotelchocolat.co.jp/',
            'tel' => '097-574-6166',
            'service' => 'ホテルショコラは、もったいない精神に基づきフードロスを減らすため、賞味期限が11月末までの商品を最大40%OFFで販売します。イギリスからやってくるチョコレートは、風味をそのままにお届けする為に、添加物を控えナチュラルな原料を使用し、冷凍しないまま店舗に並びます。その為、美味しく召し上がれる期間(Best Before End)を、短く設定しています。食べごろ期限が迫った商品を、期間限定の特別価格にてご提案させていただきます。',
            'picture1' => 'https://www.oitadrip.jp/zwp/wp-content/uploads/2021/06/hotel2-1-1024x683.jpg',
            'picture2' => 'https://www.oitadrip.jp/zwp/wp-content/uploads/2021/06/hotel3-1024x683.jpg',
            'picture3' => 'https://cdn.shopify.com/s/files/1/0026/0233/6326/files/S__12886018.jpg?v=1622797779',
            'picture4' => '',
            'parking' => '有',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23314',
            'longitude' => '131.60743',
            'review_count' => '2',
            'star' => '3',
            'end_time' => '20:00',
            'start_time' => '10:00'
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'ナナズグリーンティー',
            'address' => '大分県大分市要町1-14 アミュプラザおおいた 2F',
            'link' => 'http://www.nanasgreentea.com/',
            'tel' => '097-574-8088',
            'service' => '茶の湯の世界では、お客様に喜んでいただけるよう、「茶」のみならず様々なかたちでおもてなしの想いを表現しています。nana’s green teaでも、商品やインテリア、デザインなど様々なかたちで「お客様の笑顔を大切にしたい」という創業当初からの想いを表現しています。そして、茶の湯の心や日本の食文化など、世代をこえて日本で親しまれてきた良いものを、 現代の生活の中でより親しみ、楽しめるように「新しい日本のカタチ」として提供しています。',
            'picture1' => 'https://cdn.4travel.jp/img/thumbnails/imk/tips_pict/18/83/80/650x450_18838068.jpg',
            'picture2' => 'https://images.keizai.biz/hamakei/headline/1342504917_photo.jpg',
            'picture3' => 'https://www.shigotoba.net/_img/casestudy/space/99382ADEFC1CAF43750A14B2966447642.jpg',
            'picture4' => '',
            'parking' => '有',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23391',
            'longitude' => '131.60654',
            'review_count' => '4',
            'star' => '10',
            'end_time' => '20:00',
            'start_time' => '10:00'
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'きくたろう',
            'address' => '大分県大分市要町1-14 アミュプラザおおいた 1F',
            'link' => 'https://kikutaro.shop/?gclid=EAIaIQobChMIhteb0PeB-wIVgcuWCh04wA8zEAAYASAAEgK4UfD_BwE',
            'tel' => '097-513-1220',
            'service' => 'かりんとうの他にもおはぎや串団子、揚げ饅頭など伝統的で心休まる和菓子や、sweets shop FAVORI PLUSとコラボレートした洋菓子のテイストを取り入れた和菓子の数々、プレゼントや進物におすすめなギフトなど、どのようなシーンでもご利用いただけるお菓子を取り揃えております。私たちはすべてのお客様のそばに寄り添うお店で在り続けたいと思っております。',
            'picture1' => 'https://sweetsinfonews.com/wp-content/uploads/2022/08/img_630215396dce6.jpg',
            'picture2' => 'https://tabicoffret.com/assets_c/2019/05/IMG_6736-thumb-autox933-113351.jpg',
            'picture3' => 'https://www.kikutaro.net/uploads/1/1/7/2/117232879/kiku-210405-i09-2_orig.jpg',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23372',
            'longitude' => '131.60620',
            'review_count' => '4',
            'star' => '3',
            'end_time' => '20:00',
            'start_time' => '10:00',
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => '亜李蘭',
            'address' => '大分県大分市東大道1-3-1 アクロスプラザ大分駅南 1F',
            'link' => 'https://ariran-group.com/index.html',
            'tel' => '097-529-6679',
            'service' => '大分の焼肉は亜李蘭グループ厳選された安心・安全な牛肉を提供します',
            'picture1' => 'https://rimage.hitosara.com/gg/image/0006048348/0006048348E1.jpg',
            'picture2' => 'https://blog-imgs-115.fc2.com/o/i/t/oitatabearuki/resize1037.jpg',
            'picture3' => 'https://ooita.goguynet.jp/wp-content/uploads/sites/19/2018/06/7bf325019410e4d8a846f40f31db6927-768x318.jpg',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23280',
            'longitude' => '131.60497',
            'review_count' => '6',
            'star' => '3',
            'end_time' => '23:00',
            'start_time' => '11:00'
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => '目利きの銀次',
            'address' => '大分県大分市東大道1-3-1 KCAアクロスプラザ大分駅南 1F',
            'link' => ' https://www.monteroza.co.jp/brand/gin/',
            'tel' => '097-544-9088',
            'service' => '漁師の宴 開演！豊富な海の幸を取り揃えて今宵も一杯やりましょう！全国各地の漁港や漁師さんから「目利き」が選んだ旬の鮮魚を仕入れました。自分で焼く磯の香りの漂う『濱焼』など豪快な漁師料理をうまいお酒で楽しめるお店です。',
            'picture1' => 'https://rimage.gnst.jp/rest/img/2598z7480000/s_0qng.jpg?t=1652249075&g=670',
            'picture2' => 'https://phrase-oita.com/wp-content/uploads/2016/12/20161227107.jpg',
            'picture3' => 'https://tblg.k-img.com/restaurant/images/Rvw/74836/640x640_rect_74836562.jpg',
            'picture4' => '',
            'parking' => '有',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23323',
            'longitude' => '131.60495',
            'review_count' => '10',
            'star' => '3',
            'end_time' => '0:00',
            'start_time' => '17:00',
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'ドトールコーヒー',
            'address' => '大分県大分市末広町1-1-33',
            'link' => ' https://www.doutor.co.jp/',
            'tel' => '097-534-2900',
            'service' => '万全なバックアップ体制で加盟店をサポートします。',
            'picture1' => 'https://media-cdn.tripadvisor.com/media/photo-s/0d/c0/14/d6/dsc-4716-largejpg.jpg',
            'picture2' => 'https://livedoor.blogimg.jp/oita_morning/imgs/9/e/9ef5f4d8.jpg',
            'picture3' => 'https://d2j6doapa7j1ze.cloudfront.net/upload_picture/S1432026042970_1.jpg',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23469',
            'longitude' => '131.60637',
            'review_count' => '3',
            'star' => '4',
            'end_time' => '22:00',
            'start_time' => '7:00',
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => '串カツ田中',
            'address' => '大分県大分市要町1-14 アミュプラザおおいた 1F',
            'link' => ' https://kushi-tanaka.com/',
            'tel' => '097-574-5582',
            'service' => 'ソースの二度づけ禁止の名物串カツ、大阪伝統の味。色々なシーンに利用できるお得な宴会コースをご用意。串カツに合うお酒を取り揃えています。',
            'picture1' => 'https://images.keizai.biz/oita_keizai/photonews/1568273406_b.jpg',
            'picture2' => 'https://phrase-oita.com/wp-content/uploads/2019/08/201908221814.jpg',
            'picture3' => 'https://paypaygourmet-pctr.c.yimg.jp/hhwo1Z4ujz3lqiHcC_Zvvwfod3F-tH-IhS4xrpYuy2PBIP6C0rieDxLjxRzL7GYmsdOtuAgv1C_9rIn40LdysjHu_68wDV2TO8TWGhwzhs77YYiF1k1F9_3RPBg9J8qlIzHUm2DLwJN765o83Z84dQ==',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23311',
            'longitude' => '131.60608',
            'review_count' => '12',
            'star' => '4',
            'end_time' => '0:00',
            'start_time' => '11:00'
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'トランドール',
            'address' => '大分県大分市要町1-1',
            'link' => ' https://www.traindor.com/shop/?id=oita',
            'tel' => '097-513-8088',
            'service' => 'いつもの朝ごはんに。出張や旅行で電車に乗る前に。お買い物の寄り道に。九州・山口の駅・ショッピングセンターで、焼きたてのパンをご用意してお待ちしております',
            'picture1' => 'https://tabelog.com/restaurant/images/Rvw/53957/640x640_rect_53957158.jpg',
            'picture2' => 'https://stat.ameba.jp/user_images/20200205/05/motoyuki2013/89/8d/j/o1080081014707958624.jpg',
            'picture3' => 'https://www.traindor.com/breads/img/meal/mv.jpg',
            'picture4' => '',
            'parking' => '有',
            'area_id' => '1',
            'perfecture_id' => '44',
            'latitude' => '33.23359',
            'longitude' => '131.60642',
            'review_count' => '13',
            'star' => '3',
            'end_time' => '21:00',
            'start_time' => '6:30',
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => '与八郎 Cafe&Sweets',
            'address' => '大分県別府市鉄輪風呂本1組',
            'link' => ' https://www.instagram.com/yohachiro_cafesweets/',
            'tel' => '0977-27-7002',
            'service' => '別府市鉄輪のいでゆ坂にスイーツやデザートが自慢のカフェ',
            'picture1' => 'https://phrase-oita.com/wp-content/uploads/2016/08/201608261418.jpg',
            'picture2' => 'https://beppu-yufu-hita.goguynet.jp/wp-content/uploads/sites/171/2021/09/9A9C5394-7040-4BC3-94B6-B18150D081A9.jpeg',
            'picture3' => 'https://phrase-oita.com/wp-content/uploads/2016/07/20160725024.jpg',
            'picture4' => '',
            'parking' => '有',
            'area_id' => '2',
            'perfecture_id' => '44',
            'latitude' => '33.31663',
            'longitude' => '131.47815',
            'review_count' => '10',
            'star' => '4',
            'end_time' => '17:00',
            'start_time' => '11:00'
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => '地獄蒸し工房 鉄輪',
            'address' => '大分県別府市風呂本5組(いでゆ坂沿い)',
            'link' => 'http://jigokumushi.com/',
            'tel' => '0977-66-3775',
            'service' => '摂氏98度、100%地熱エネルギーの温泉噴気を利用した、別府鉄輪温泉では江戸時代から用いられていた伝統の調理法「地獄蒸し料理」を体験できる施設です。その他にも、温泉冷却装置モニュメント「湯冷滝（ゆれいだき）」や「飲湯場」、隣りのポケットパークには「足蒸し」や車椅子の方でもご利用いただける「足湯」も完備しております',
            'picture1' => 'https://ps-q.jp/wp-content/uploads/2019/07/（提供：別府市観光課）地獄蒸し工房-鉄輪_005.jpg',
            'picture2' => 'https://www.mapple.net/cms/wp-content/uploads/2018/01/16311.jpg',
            'picture3' => 'https://www.city.beppu.oita.jp/images/sisetu/sangyou_kankou/11-17jigokumushi.jpg',
            'picture4' => '',
            'parking' => '有',
            'area_id' => '2',
            'perfecture_id' => '44',
            'latitude' => '33.31635',
            'longitude' => '131.47622',
            'review_count' => '3',
            'star' => '3',
            'end_time' => '19:00',
            'start_time' => '10:00',
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'みゆき食堂',
            'address' => '大分県別府市御幸2',
            'link' => 'https://www.instagram.com/explore/tags/%E3%81%BF%E3%82%86%E3%81%8D%E9%A3%9F%E5%A0%82/?hl=ja',
            'tel' => '0977-66-1308',
            'service' => 'お店は、ご主人が脱サラして20歳のときに開店。現在はご夫婦で切り盛りし、二人の温かい人柄もあって常連客で賑わっています。',
            'picture1' => 'https://www.tabirai.net/sightseeing/column/img/0005314/kiji1Img.JPG',
            'picture2' => 'https://pic1.homemate-research.com/pubuser1/pubuser_facility_img/9/8/3/14092759389/0000026310/14092759389_0000026310_1.jpg',
            'picture3' => 'https://www.tabirai.net/tabirai-uploader/img/0020963/s1_0020963.jpg',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '2',
            'perfecture_id' => '44',
            'latitude' => '33.31624',
            'longitude' => '131.47539',
            'review_count' => '8',
            'star' => '2',
            'end_time' => '20:30',
            'start_time' => '10:30',
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'まさ食堂',
            'address' => '大分県別府市鉄輪風呂本5',
            'link' => 'https://www.kannawa-yunoka.com/info/%E6%B9%AF%E5%B7%A1%E3%82%8A%E3%81%AE%E8%85%B9%E3%81%94%E3%81%97%E3%82%89%E3%81%88%E3%81%AB%E2%98%86%E3%81%BE%E3%81%95%E9%A3%9F%E5%A0%82/',
            'tel' => '0977-66-0684',
            'service' => '大分県には美味しい物がたくさんあります。海の幸も山の幸も豊富です。',
            'picture1' => 'https://tabelog.com/restaurant/images/Rvw/98585/640x640_rect_98585480.jpg',
            'picture2' => 'https://cdn.4travel.jp/img/thumbnails/imk/tips_pict/18/75/56/650x450_18755657.jpg',
            'picture3' => 'https://media-cdn.tripadvisor.com/media/photo-s/09/19/c6/d1/caption.jpg',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '2',
            'perfecture_id' => '44',
            'latitude' => '33.31662',
            'longitude' => '131.47597',
            'review_count' => '14',
            'star' => '4',
            'end_time' => '14:30',
            'start_time' => '11:00',
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'tiny little deli',
            'address' => '大分県別府市御幸2',
            'link' => 'https://www.facebook.com/tld0920/',
            'tel' => '080-5964-1260',
            'service' => ' 鉄輪、いでゆ坂そばの元たばこ屋さんでちっちゃなお惣菜屋さんをしてい',
            'picture1' => 'https://beppu-yufu-hita.goguynet.jp/wp-content/uploads/sites/171/2021/05/62A3F4DB-AAFD-4114-8AF8-C089281598D1.jpeg',
            'picture2' => 'https://livedoor.blogimg.jp/nekomuranaturu/imgs/9/3/932baf5e.jpg',
            'picture3' => 'https://imgfp.hotp.jp/IMGH/95/21/P036079521/P036079521_480.jpg',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '2',
            'perfecture_id' => '44',
            'latitude' => '33.31613',
            'longitude' => '131.45572',
            'review_count' => '8',
            'star' => '4',
            'end_time' => '16:00',
            'start_time' => '7:00'
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => '茶寮 大路',
            'address' => '大分県別府市風呂本5',
            'link' => ' http://www.lets-begin.info/ooji/',
            'tel' => '0977-66-0011',
            'service' => '評判の茶そばや鯛の骨蒸し、野菜が美味しく食べられると人気の「ご馳走」地獄蒸し等',
            'picture1' => 'https://cdn-mapple.net/Normal/大分県/44010327_3895_2.jpg',
            'picture2' => 'https://tabelog.com/restaurant/images/Rvw/77830/640x640_rect_77830418.jpg',
            'picture3' => 'https://fastly.4sqi.net/img/general/600x600/150926306_w212AWu5AHwDvE0Z2EhMMton-nQYnEKYwVqNaNwScyA.jpg',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '2',
            'perfecture_id' => '44',
            'latitude' => '33.31641',
            'longitude' => '131.47577',
            'review_count' => '11',
            'star' => '3',
            'end_time' => '21:00',
            'start_time' => '11:00'
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => '伊藤商店',
            'address' => '大分県別府市鉄輪風呂本5組',
            'link' => ' https://www.facebook.com/Ito.shouten.maruichi/',
            'tel' => '0977-51-5925',
            'service' => '大分県別府市鉄輪温泉近くにあります、お食事処、居酒屋です、魚屋がし',
            'picture1' => 'https://e-holiday.net/wp-content/uploads/beppu-oita-gourmet-5.jpg',
            'picture2' => 'https://ak-d.tripcdn.com/images/1i61j223488jolrg0A32F_R_600_400_R5_Q90.jpg?proc=source/trip',
            'picture3' => 'https://static.yukoyuko.net/photo/3276/dinner/a1u6F000006xiPXQAY/0001_600.jpg',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '2',
            'perfecture_id' => '44',
            'latitude' => '33.31653',
            'longitude' => '131.47625',
            'review_count' => '8',
            'star' => '4',
            'end_time' => '22:00',
            'start_time' => '11:00',
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => 'とり若',
            'address' => '大分県別府市鉄輪御幸2組',
            'link' => 'https://shachuhaku-camp.com/gourmet/toriwaka-180428/',
            'tel' => '0977-66-1088',
            'service' => '食べ始めると止まらない！鉄輪「とり若」の唐揚げが美味',
            'picture1' => 'https://cdn.4travel.jp/img/thumbnails/imk/tips_pict/18/99/34/650x450_18993467.jpg?updated_at=1667860717',
            'picture2' => 'https://img01.jalannews.jp/img/2019/08/20190806_oita_05.jpg',
            'picture3' => 'https://cdn.4travel.jp/img/thumbnails/imk/tips_pict/17/09/22/650x450_17092277.jpg?updated_at=1580205968',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '2',
            'perfecture_id' => '44',
            'latitude' => '33.31629',
            'longitude' => '131.47557',
            'review_count' => '4',
            'star' => '3',
            'end_time' => '17:30',
            'start_time' => '9:00'
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => '鉄輪むし湯',
            'address' => '大分県別府市鉄輪上1組',
            'link' => 'https://www.city.beppu.oita.jp/sisetu/shieionsen/detail11.html',
            'tel' => '0977-67-3880',
            'service' => 'ここのむし湯は独特の形式をとっており、1メートル四方の木戸を開けて中に入ると約8畳ほどの石室があります。 温泉で熱せられた床の上には石菖（せきしょう）という清流沿いにしか群生しない薬草が敷きつめられていて、 その上に人が横たわります。石菖はすばらしい香りで、「豊後鉄輪、むし湯の帰り、肌に石菖の香が残る」と 詩人の野口雨情が詠っているほどです。',
            'picture1' => 'https://www.city.beppu.oita.jp/images/sisetu/shieionsen/11-09kannawa.jpg',
            'picture2' => 'https://i0.wp.com/tabi-mag.jp/wp-content/uploads/OT005401.jpg?w=1200&ssl=1',
            'picture3' => 'https://onsen.nifty.com/kk_image/view/onsen/onsen-detail/onsen004505/0000205275.jpg',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '2',
            'perfecture_id' => '44',
            'latitude' => '33.31699',
            'longitude' => '131.47818',
            'review_count' => '6',
            'star' => '4',
            'end_time' => '19:30',
            'start_time' => '7:30',
        ];
        DB::table('stores')->insert($param);
        $param = [
            'store_name' => '渋の湯',
            'address' => '大分県別府市鉄輪風呂本16',
            'link' => 'https://www.owl.ne.jp/shibunoyu/about.html',
            'tel' => '444-444-444',
            'service' => '高温の温泉が竹枝を伝って落ちるあいだに冷却される竹製温泉冷却装置『湯雨竹』での温度調節により、源泉そのままの掛け流し温泉が楽しめます。',
            'picture1' => 'https://cdn-ak.f.st-hatena.com/images/fotolife/K/Kazdorado/20170627/20170627204708.jpg',
            'picture2' => 'https://onsendo.beppu-navi.jp/wp-content/uploads/2021/02/38shibunoyu.jpg',
            'picture3' => 'https://cdn.jalan.jp/jalan/img/4/kuchikomi/5374/KL/c2d64_0005374311_1.JPG',
            'picture4' => '',
            'parking' => '無',
            'area_id' => '2',
            'perfecture_id' => '44',
            'latitude' => '33.31686',
            'longitude' => '131.47743',
            'review_count' => '9',
            'star' => '3',
            'end_time' => '21:00',
            'start_time' => '6:30'
        ];
        DB::table('stores')->insert($param);
    }
}
